language: python
install: "pip install -e ."
script: nosetests

jobs:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - stage: publish
    python: "3.6"
    script: true
    deploy:
      provider: pypi
      user: pc
      password:
        secure: "KRxFiLrtrLLC4ep/VZRE7eVzE5HVOPg0ZjD7+tmBluTG7e9c3RPzH1YoY3KpnvMH32FDyKH4FfDN1adq1edKvx+TnM+CgdmlqTIkrznsAIDEbStDae6S7We/OU2yU8p27eQtnwCu7TaGAvm+7M1ZtN/FJDhaS6ba0J4Wotnz+UcDEu6cj1nZK9t99G+LxKnNvS+OzTZ2ie520ppn1PHY5K8DPG12AZjAcIXZV92knagtigB767g/BSpyNy061mRhoS9J5wlXUxjgh8JDvXfTpqgazbW0352JutW7uSU7WJ8mTj1kJTMOiZIIDbNUqEWHsMjevjjevhqeZI/2m3VfY1U2ktb0UvWyNMFOY2L9t0a7E85n36lEsQEUMPYeWWaUjn7acregQJcuJ8aHmsg27nK4U4n4a8CWXaME2v9HnF89PtUtKkQpol9NYb13syWqfIkPQpVSsphT47C6eF5B+m01JXyKjW8TNbB+h1x8DtTP/CS67hlTmf8fVDhzYWpOoh2u9YbZw+kJz49iPfIR3g0QQVqmG0TFFeWcrIAN60k614z30ZG6tkbvH/fZfuRxHivE1NdE/wGwl34jXdL1VCk3fcdDyDhs68aUNipvHP1sZkt6rDqvVlcNOSbgGdK8/A+IQLQc34cd3MBA+b3Nfj5NMZ2hsh4TTevWS9r/7JM="
      distributions: "sdist"
      on:
        tags: true
        python: 3.6
